name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'  # Toutes les 6 heures pour coïncider avec la limite

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 355  # 5-10 minutes de marge pour éviter les coupures brutales

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install ffmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Install dependencies
      run: |
        npm install -g pm2
        npm install --legacy-peer-deps

    - name: Start application with max runtime
      run: |
        # 21480 secondes = 5h58m (marge de sécurité)
        timeout 21480s npm run zokou